id: P006801
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8369
  title: ཡན་ལག་བརྒྱད་པའི་གཞུང་ལས་བསྡུས་པའི་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    4edf691716d94af789bb0f3a702c878b:
      image_group_id: I3CN8371
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
